language: python
sudo: required
dist: trusty

python:
    - "2.7"
    - "3.4"
    
virtualenv:
  system_site_packages: false

# command to install dependencies
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libopenblas-dev liblapack-dev gfortran
    
install: 
    - pip install --upgrade pip
    - pip install -r python/requirements.txt
    - cd python 
    - ls -l
    - ln -s ../src .
    - python setup.py install

# command to run tests
script: true


