language: python
sudo: false
dist: trusty

python:
    - "2.7"
    - "3.4"
    
cache: apt
addons:
  apt:
    packages:
    - libopenblas-dev
    - liblapack-dev
    - gfortran

    
#virtualenv:
#  system_site_packages: false

# command to install dependencies
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda    
  
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy nose
  - pip install pep8 python-coveralls
  - pip install .
    
#install: 
#    - pip install --upgrade pip
#    - pip install -r python/requirements.txt
#    - cd python 
#    - ls -l
#    - ln -s ../src .
#    - python setup.py install

# command to run tests
script: true


