language: python
sudo: false
dist: trusty

python:
- '2.7'
- '3.4'

cache: apt

addons:
  apt:
    packages:
    - libopenblas-dev
    - liblapack-dev
    - gfortran

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy nose
    - cd python
    - ln -s ../src .
    - pip install .

script: true

deploy:
  provider: pypi
  user: jochym
  password:
    secure: GI6iKqz/Bmxu8IxP442M4FCH3m7thd+lJjHH1aO37ClSzmLm9Y0fAyXkIaN/aW66yMT4yx6cRZ0EgQBrIF6DlY3DvnnA+qM0K3MNz1gMs3BCQ+AO+r9wRF0jnC4WUtgIXgiYbmYDXWPafT8lsQbRgsrcU5daSoK9N9kM7V8kWYZbG/XRdoOQuGn5G3k6WURJC4eI0iwxAgNyYhnmcquBbE6WwgH+Eoi4rOI0cNfLgZtk2mDNbRWC82VBuSSx3x8w/8nagfuWOZYBAb1Z0+vfUZhnrQgIveqIvxgnSSsFIc2TIoSANSwZ+44nIBQwlhK5a3yCm15BtEtq1lbslHFptAO+c9T7PfS0RZOIzBxAEBB1CZ+2vgE3ZBfPM7gxl3PhDWEcwEqktydW+J4sKs/Pz7zFtn4P3lSsHaVInQrTrouuFLn8DO4ZUS8XVLRtkqA1CX6cJHIs8qtG1cVjAku6BNtxGXaf69ZP4aMjphP3t1npWQqPw4Aiv30aF8tFu6KzS2El4ZcQd3Mn5CsKV4Rvq54XsDJeXDvlXHrr0gPT7vRaOi5kdsBvX/a8x+9VP9kG+4Dth7GGAJ4jtvc8M8XnxbT1r7KOX+/KY1VdgC8n6pVRICUsp6ckAvxyKCUhKf3RAJYf4+R+1NQFq/vdVtkfHaMbFRFdIxjk6gRA3zGMKZ8=
  on:
    tags: true
    branch: master
