language: python
sudo: false
dist: trusty

python:
- '2.7'
- '3.4'
- '3.5'

cache: apt

addons:
  apt:
    packages:
    - libopenblas-dev
    - liblapack-dev
    - gfortran

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy
    - aclocal
    - autoheader
    - libtoolize # or glibtoolize on mac
    - touch INSTALL NEWS README AUTHORS
    - automake -acf
    - autoconf
    - ./configure
    - make
    - cd python
    - pwd
    - git branch -v
    - git describe --tags --dirty
    - ./get_nanoversion.sh
    - cat __nanoversion__.txt
    - ln -s ../src .
    - python setup.py install 

script:
    - cd test
    - python test_spglib.py
    - cd ..

deploy:
    # testing
    provider: pypi
    server: https://testpypi.python.org/pypi
    skip_cleanup: true
    distributions: sdist
    user: jochym
    password:
        secure: "JBSrOM59mYHCInktXcbERawSb1cbEVkAAoY4Fq9xdXQfZgkrQQDrEKvsm3neH9RNUr66DvfNk4UDjil5xWF0hJTPoX0UAu7gHRuGnnsXwSwgvCMQ37/FvZnMXZp7zA7w0VfPEjK4FWcYincioqS6AewPsJaF4Dsp4W/bnIomZ3EhASvNn1oj7vqlhXhACGA9ZhZNROurhfqaUChSuefe7ze7idfKhJX0bhS5U+DGCaED8EdYRCQHaekbwy+WAin2YQIMxbxCsdoBoaoaTtUoR+k//O6/Jjb2QzsFgnP3JwCG9GlohyVOeBJlnLHkM7zGhfE4yzr1f4i8o6pePXKOhiZ0CjMVA6zQlMl4Aqe6vzAF00lOySV8radtXWI8Aevx0A1Z2diSMrTjnSWAglKph3vJGM1jzvEEc3M7shij0b3IfqohAT2M8oUPHE81MnhlVKf6QdkIy04eCi/ne3L2zTyTvILz1JMnnKSSbSH9vgZIaKDBtRz56lZmsDdhmCs9HlzB7uQNVTpmNRhPudiREMBFsh/OmqL0d9WsbalXaYVljlunHpuAVJKQynX2CEvyeOxELpjWU1W9mbItFqvXdnXHMX8eYLK6RYlJp5DR/QS3Ev6ldY6cURqj0EsL0RZxEwR02+pyiT6CC8ZtCC/isAKoQvHxKHwI0OG2y6z0i8Y="
    on:
        branch: pypifix
        tags: false
        python: 2.7
    # production
    provider: pypi
    skip_cleanup: true
    distributions: sdist
    user: jochym
    password:
        secure: GI6iKqz/Bmxu8IxP442M4FCH3m7thd+lJjHH1aO37ClSzmLm9Y0fAyXkIaN/aW66yMT4yx6cRZ0EgQBrIF6DlY3DvnnA+qM0K3MNz1gMs3BCQ+AO+r9wRF0jnC4WUtgIXgiYbmYDXWPafT8lsQbRgsrcU5daSoK9N9kM7V8kWYZbG/XRdoOQuGn5G3k6WURJC4eI0iwxAgNyYhnmcquBbE6WwgH+Eoi4rOI0cNfLgZtk2mDNbRWC82VBuSSx3x8w/8nagfuWOZYBAb1Z0+vfUZhnrQgIveqIvxgnSSsFIc2TIoSANSwZ+44nIBQwlhK5a3yCm15BtEtq1lbslHFptAO+c9T7PfS0RZOIzBxAEBB1CZ+2vgE3ZBfPM7gxl3PhDWEcwEqktydW+J4sKs/Pz7zFtn4P3lSsHaVInQrTrouuFLn8DO4ZUS8XVLRtkqA1CX6cJHIs8qtG1cVjAku6BNtxGXaf69ZP4aMjphP3t1npWQqPw4Aiv30aF8tFu6KzS2El4ZcQd3Mn5CsKV4Rvq54XsDJeXDvlXHrr0gPT7vRaOi5kdsBvX/a8x+9VP9kG+4Dth7GGAJ4jtvc8M8XnxbT1r7KOX+/KY1VdgC8n6pVRICUsp6ckAvxyKCUhKf3RAJYf4+R+1NQFq/vdVtkfHaMbFRFdIxjk6gRA3zGMKZ8=
    on:
          branch: master
          tags: true
          python: 2.7
