language: python
sudo: false
dist: trusty

python:
- '2.7'
- '3.5'

cache: apt

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy anaconda-client anaconda-build
    - aclocal
    - autoheader
    - libtoolize
    - touch INSTALL NEWS README AUTHORS
    - automake -acf
    - autoconf
    - ./configure
    - make check # test in C
    - cd python
    - pwd
    - git branch -v
    - git describe --tags --dirty
    - ./get_nanoversion.sh
    - cat __nanoversion__.txt
    - ln -s ../src .
    - python setup.py install 

script:
    - cd test
    - python test_spglib.py
    - cd ..

deploy:
    # testing pypi
    - provider: pypi
      server: https://testpypi.python.org/pypi
      skip_cleanup: true
      distributions: sdist
      user: atztogo
      password:
          secure: "Po6vOS9TlkXHD8SBbQxPkZHWzekpk99YnxFmKRILsZpNw32MJk039wTkDEz3e3XJkNIWdAK3dhfkxkJgnwpeBwUlYCGSU5FdNsTpqJDhLtEDkhq1rs1icL/P0C2Y4X0QMIug32HlQQU2kNzi+rS0ldB/TSEInrIoSw98r50SQt5mTPGjxVQ0LC9HdLCKEjdGAry8zY+n6IgoF+YxwB2F85Wr480bbYMhgNt+LCt99ABcTDZd7CI9qmBUgXAacOCLfpcMG36gnAZrN4wOQia8TnlHLP9bPTc7jRk8KW/2NOFFjbbwTmtEHQeB3lxC2lfGEEiqyHCDo3cpv0DR683M/KpIdDBUONbIaKAJLg5Ty/993jAhetnlLTZOYoDPX6LnUDoOcSF+33JEikG2c5xTs7oqGM1KJiK5gOp8aWUA7D5kHmv0a2GxhK19xZ5So/qJpxDuOgwzoc5RxPgpzt/T2uk4lX4LiQrB1fA2TRA7Vl7kN2QJjCTzCbB4AamRoDCAsBAix4arKHNrYpXgouXOx9Dbr6x7VsMFr184BdJyT2nsi1XpqBabdopK41c6atZQBQggzBcYWs1qlkJb0ISf+P6SklyCgXGX4djH6+UwMmVG15cSc4AS7Z9peGP3LoGpv2QmtbSwmmr/AnOLL1puK8OFd45whI/BTcdfhksWqiY"
      on:
        repo: atztogo/spglib
        branch: rc
        tags: false
    
    # testing conda
    - provider: script
      skip_cleanup: true
      script: conda/anaconda_deploy.sh rc $ANACONDA_TOKEN $TRAVIS_BRANCH
      on:
        repo: atztogo/spglib
        branch: rc
        tags: false

    # production pypi
    - provider: pypi
      skip_cleanup: true
      distributions: sdist
      user: atztogo
      password:
          secure: "sjUxbFSrhflB/NqMwcJCmalmQRX1EN4zgsK2YyY93JEk16aep+5pRyV87Q3Q54L19PGOkTqOrGyvUhwxTHUweo87F2DM1gd695bg0rROcquvhwWxlTuhMhMoUGSxDljgKbEeTvLikFd91JX2Rr/deIZLog/c3z/m55MbgHqGoyR5p1twxqLoUcJHznM8Mnn/KTauVHVQKG/6sVQr/h9AhRB8qI5VRCcrnDqAWoePqkgibWjEKchx/lmgW4TiB15IIvmIVgMxNwUa2q91Lqn3AhZDOcB/TST34yZCx8j1TpLJgAtB8+aRnTdmtfhnPWN8gebVuHJni+EQYsq4sIOiRzsU5qHkCzmW2x6I/kcTTYWYW4KybKorWQcypotTkyDoSfFuhZ93kyMy6QXBdV0/3xskBAbA++Mc93u6KaNMDnBGLb9PoeIT6R6YRNnwDAYBSlJ8lMZoNwVKrPhxI11r15eAK/4NamUHSLORBJWYKw1Z1Ko5wjkMXTSC4y7rC5UD+wrgZCfhB7WBLvatGBA3oD83dmEzMl3zA3wyaegDqHbEzKIFCGX5/eKrVN91hQrvlFkVYwf7YHAcNTvplZi0EGotfuZVsyhHiYSXRrMdF16g/NyZwunMEydafsbbwQatLxMhCMufX+5B1bk8VsmM0QDI9EV3rdvC7vgpnO5KPpY="
      on:
        repo: atztogo/spglib
        branch: master
        tags: false

    # production anaconda
    - provider: script
      skip_cleanup: true
      script: conda/anaconda_deploy.sh main $ANACONDA_TOKEN $TRAVIS_BRANCH
      on:
        repo: atztogo/spglib
        branch: master
        tags: false
